@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.inspirations;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
