@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.inspirations.tools.capability;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
