@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.inspirations.tweaks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
