@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.inspirations.tweaks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
