@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.inspirations.recipes.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
