@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package knightminer.inspirations.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
